### ISSUE TITLE
Create `age_at_visit` variabel

### ISSUE THREAD

**Issue by andkov** [dss-ialh/displaying-health-data#9]
@wibeasley , please create a variable `age_at_visit` with a day precision. We will also want a `date_of_birth` that we can derived from it. Or vice-versa.

**Comment by wibeasley** [comment]
@andkov, when we come back to this, I think we could create the universe of possible dobs with [`seq.Date()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/seq.Date.html), and then sample from the universe.

Then calculate age from the `dob` and `date_at_visit` columns.
